apps/login/urls.py
from django.conf.urls import url
from . import views

app_name = 'login'
urlpatterns = [
    url(r'^$', views.index, name='login'),
    url(r'^process$', views.process, name='process_login'),
    # url(r'^success$', views.show),
    # url(r'^logout$', views.logout),
]

wish_list/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.login.urls', namespace='login')),
    url(r'^', include('apps.wishList.urls', namespace='wishList')),
]

apps/login/models.py
from __future__ import unicode_literals

from django.db import models
import re
import bcrypt

EMAIL_REGEX = re.compile(r'^[a-zA-z0-9\.\+_-]+@[a-zA-Z0-9\._-]+\.[a-zA-Z]*$')

# Create your models here.
class UserManager(models.Manager):
    def new_user(self, data):
        errors = []
        print data
        print '9'*50

        if len(data['first_name']) < 3:
            errors.append('Please enter a valid First Name')
        # elif not data['first_name'].isalpha():
        #     errors.append('Please enter a valid First Name')

        if len(data['last_name']) < 3:
            errors.append('Please enter a valid Last Name')
        # elif not data['last_name'].isalpha():
        #     errors.append('Please enter a valid Last Name')

        if len(data['user_name']) < 3:
            errors.append('Please enter a User Name')

        if len(data['email']) < 1:
            errors.append('Please enter your email')
        elif not re.match(EMAIL_REGEX, data['email']):
            errors.append('Please enter a valid Email address')
        else:
            u_email = data['email']
            try:
                User.objects.get(u_email=email)
                errors.append('Email already exists.  Please enter a valid email or login.')
            except:
                pass

        if len(data['password'].encode()) < 8:
            errors.append('Password must be at least 8 characters')
        elif not data['password'].encode() == data['pw_confirm'].encode():
            errors.append('Passwords do not match! Please enter matching passwords')

        if errors:
            return(False, errors)
        else:
            first_name = data['first_name']
            last_name = data['last_name']
            email = data['email']
            pw_confirm = data['pw_confirm'].encode()
            pw_hash = bcrypt.hashpw(pw_confirm, bcrypt.gensalt())
            u = User.objects.create(first_name=first_name, last_name=last_name, email=email, pw_hash=pw_hash)
            u.save()
            return(True, u)

    def login(self, data):
        errors = []
        pw = data['password'].encode()
        email = data['email']
        print '<--------- in the login function'
        if len(email) < 1:
            errors.append('Please enter your email')
        elif not re.match(EMAIL_REGEX, email):
            errors.append('Please enter a valid email')
        else:
            try:
                u = User.objects.get(email = email)
                if len(pw) < 8:
                    errors.append('Invalid password')
                elif not bcrypt.hashpw(pw, u.pw_hash.encode()) == u.pw_hash:
                    errors.append('Invlaid password')
            except User.DoesNotExist:
                errors.append('Please register before logging in')

        if errors:
            print '***** So Many ERRORS!!!!!******'
            return(False, errors)
        else:
            return(True, u)

class User(models.Model):
    first_name = models.CharField(max_length=45)
    last_name = models.CharField(max_length=45)
    email = models.CharField(max_length=100)
    pw_hash = models.CharField(max_length=255)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)

    objects = UserManager()

apps/login/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.contrib import messages
from .models import User

# Create your views here.
def index(request):
    try:
        messages
    except:
        pass
    return render(request, 'login/index.html')

def process(request):
    if request.method == 'POST':
        if request.POST['process'] == 'register':
            add_user = User.objects.new_user(request.POST)
            if add_user[0] == False:
                messages.error(request, add_user[1])
                return redirect('login:login')
            else:
                # request.session['name'] = add_user[1].first_name
                request.session['id'] = add_user[1].id
                messages.success(request, 'Successfully registered!')
                return redirect('wishList:dashboard')

        elif request.POST['process'] == 'login':
            u_log = User.objects.login(request.POST)
            if u_log[0] == True:
                request.session['name'] = u_log[1].first_name
                request.session['id'] = u_log[1].id
                messages.success(request, 'Successfully logged in!')
                return redirect('wishList:dashboard')
            else:
                messages.error(request, u_log[1])
                return redirect('login:login')
        else:
            return redirect('login:login')

# def show(request):
#     return render(request, 'login/success.html')
#
# def logout(request):
#     request.session.clear()
#     return redirect('/')

apps/login/templates/login/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Login | Registration</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/skeleton/2.0.4/skeleton.css">
    <style media="screen">
      p.error_red{
        color: red;
      }
      p.success_green{
        color:green;
      }
      h4, form, div.register, div.login{
        display: inline-block;
        vertical-align: top;
      }
      div.register, div.login{
        margin: 10px 5px;
        padding: 5px;
        border: solid black 3px;
      }
    </style>
  </head>
  <body>
    <div class="errors">
      {% if messages %}
        {% for message in messages %}
          <p class="error_red">{{ message }}</p>
        {% endfor %}
      {% endif %}
    </div>
    <h1>Welcome!</h1>
  <div class="register">
    <h4>Registration</h4><br>
    <form class="register" action="{% url 'login:process_login' %}" method="post">
      {% csrf_token %}
      <input type="hidden" name="process" value="register">
      <label for="first_name">First Name: <input type="text" name="first_name" placeholder="John"></label>
      <label for="last_name">Last Name: <input type="text" name="last_name" placeholder="Smith"></label>
      <label for="user_name">User Name: <input type="text" name="user_name" placeholder="Ninja3000"></label>
      <label for="email">Email: <input type="email" name="email" placeholder="name@example.net"></label>
      <label for="password">Password (At least 8 characters): <input type="text" name="password" placeholder="********"></label>
      <p>*Password shuld be at least 8 characters</p>
      <label for="pw_confirm">Confirm Password: <input type="text" name="pw_confirm" placeholder="*********"></label>
      <!-- <label for="date_hired">Date Hired: <input type="date" name="date_hired"></label> -->
      <input class="button button-primary" type="submit" name="submit" value="Register">
    </form>
  </div>
  <div class="login">
    <h4>Login</h4><br>
    <form class="register" action="{% url 'login:process_login' %}" method="post">
      {% csrf_token %}
      <input type="hidden" name="process" value="login">
      <label for="email">Email: <input type="email" name="email" placeholder="name@example.net"></label>
      <label for="password">Password (At least 8 characters): <input type="text" name="password" placeholder="********"></label>
      <input type="submit" name="submit" value="Login">
    </form>
  </div>

  </body>
</html>