apps/wishList/urls.py
from django.conf.urls import url
from . import views

app_name = 'wishList'

urlpatterns = [
    url(r'^dashboard$', views.index, name='dashboard'),
    url(r'^wish_items/(?P<id>\d+)$', views.show, name='wish_item'),
    url(r'^wish_items/create$', views.create, name='new_item'),
    url(r'^dashboard/update_list/(?P<id>\d+)$', views.update_list, name='update_list'),
    url(r'^logout$', views.logout, name='logout'),
    url(r'^add_item/(?P<id>\d+)$', views.add_item, name='add_item'),
    url(r'^remove_item/(?P<id>\d+)$', views.remove_item, name='remove_item'),
    url(r'^delete_item/(?P<id>\d+)$', views.delete_item, name='delete_item'),
]
#

wish_list/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.login.urls', namespace='login')),
    url(r'^', include('apps.wishList.urls', namespace='wishList')),
]

apps/wishList/models.py
from __future__ import unicode_literals

from django.db import models
from datetime import datetime
from ..login.models import User

# Create your models here.
class WishListManager(models.Manager):
    def user_items(self, u_id):
        print u_id
        print '<--------in user_items function'
        user = User.objects.get(id=u_id)
        print user.first_name, '<--------- user object first name$$$$$$$$$'
        user_list = WishList.objects.filter(user__id=u_id)
        # user_list = User.objects.filter(items_added__id=u_id)
        print user_list, '<---------here is my list object of items by user_id'
        # print user_list[0].user.first_name, '<-----first name'
        return user_list

    def all_items(self, u_id):
        print u_id
        print '<--------in all_items function'
        # u_id = User.objects.get(id=u_id)
        all_items = self.exclude(user__id=u_id)
        print all_items, '<---------here are all the items created by other people'
        return all_items

    def new_item(self, data, u_id):
        errors = []
        if len(data['item']) < 1:
            errors.append('Please enter a valid item')
        if not len(data['item']) > 3:
            errors.append('Please enter a valid item')
        else:
            user = User.objects.get(id=u_id)
            item = data['item']
            print item, '<-------item'

            print user, '<------------ user object'
            print user.id, '<----------- user id', user.first_name, '<------ user name'
            try:
                item_match = self.get(item=item)
                errors.append('Item already exists')
                return(False, errors)
            except:
                user_id = user.id
                item_added = WishList.objects.create(item=item, created_by=user)
                item_added.user.add(user) #accessing the itermediary table to add the user object to the wishlist object
                # user.items_added.add(item_added) accessing the itermediary table to add the wishlist object to the user object
                print item_added, '<------- item added'
                return (True, item_added)
        if errors:
            print 'So MANY ERRORS!!!!'
            return(False, errors)

    def list_update(self, u_id, i_id):
        print '^^^^^^^^^^ in the list_update method ^^^^^^^'
        print i_id, '<-------item', u_id, "<--------user"
        messages = []
        try:
            user = User.objects.get(id=u_id)
            print user
            item = self.get(id=i_id)
            print item
            item.user.add(user)
            print item.user.all(), '<<<<<<<<<<<<<<<<<<-------------- this is all user objects'
            print user.items_added.all(), 'THIS SHOULD BE ITEM OBJECTS!!!!!!!'
            messages.append('You have successfully added this item to your list')
            return(True, messages, item)
        except:
            messages.append('Error: Item not added to your list')
            return(False, messages)

    def item_remove(self, i_id, u_id):
        messages = []
        try:
            user = User.objects.get(id=u_id)
            item = self.get(id=i_id)
            item.user.remove(user)
            messages.append('You have successfully removed this item')
            return(True, messages)
        except:
            messages.append('Item could not be removed')
            return(False, messages)


    def item_delete(self, i_id, u_id):
        errors = []
        try:
            item = self.get(id=i_id)
            if item.created_by.id == u_id:
                item.delete()
                errors.append('You have successfully deleted this item.')
                return(True, errors)
            else:
                errors.append('You do not have authority to delete this item.')
                return (False, errors)
        except:
            pass


class WishList(models.Model):
    user = models.ManyToManyField(User, related_name='items_added') #connected to the user table with a hidden key of items_added.  this represents all of the items that this user has added to a wishlist
    item = models.CharField(max_length=45)
    created_by = models.ForeignKey(User, related_name='items_created') #connected wishlist table with a hidden key of items_created to list
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)

    objects = WishListManager()

apps/wishList/views.py
from django.shortcuts import render, redirect
from .models import User, WishList
from django.contrib import messages

# Create your views here.
def login(request):
    return redirect('login:login')

def index(request):
    u_id = request.session['id']
    context = {
        'name': User.objects.get(id=u_id),
        'user_items': WishList.objects.user_items(u_id),
        'other_items': WishList.objects.all_items(u_id),
    }
    return render(request, 'wishList/index.html', context)
    #create a view page that lists all items in logged in user's wish list in a table
        #make a ORM call to pull all the items from the users list
    #can delete items that logged in user created
        #if user id for item matches the logged user, add button Delete
    #can remove items that logged in user added from others wish list
        #if user id doesn't match the userid for the item, add button Remove from my Wishlist
    #create a table with all the items from others wish lists

def show(request, id):
    users = User.objects.filter(items_added__id=id)
    print users, '<-----user object'
    item = WishList.objects.get(id=id)
    print item, '<-------item object'
    context = {
        'users': users,
        'item': item,
    }
    #lists a single item with a list of users who also have this item in their db
    return render(request, 'wishList/item.html', context)

def create(request):
    return render(request, 'wishList/new_item.html')

def add_item(request):
    if request.method == 'POST':
        u_id = request.session['id']
        add_item = WishList.objects.new_item(request.POST, u_id)
        print add_item, '<------- this was returned from .new_item'
        if add_item[0] == True:
            print '<___________ item added successfully'
            messages.success(request, 'Item successfully added')
        else:
            messages.error(request, add_item[1])
            return redirect('wishList:new_item')
    #validations when adding a new item: No Empty entries, should be more than 3 entries
    #should be added to the User's Wish list table
    #User should be redirected to dashboard return redirect('')
    return redirect('wishList:new_item')

def update_list(request, id):
    print '************ in the update_list function'
    u_id = request.session['id']
    u_list = WishList.objects.list_update(u_id, id)
    print u_list, '<---------------- updated list object'
    if u_list[0] == True:
        print u_list[1], '<---------- u_list[1]'
        print u_list[2], '<------------- item passed from models'
        for msg in u_list[1]:
            messages.success(request, msg)
        return redirect('wishList:dashboard')
    else:
        for msg in u_list[1]:
            messages.error(request, u_list[1])
    return redirect('wishList:dashboard')

def remove_item(request, id):
    u_id = request.session['id']
    i_remove = WishList.objects.item_remove(id, u_id)
    if i_remove[0] == True:
        for msg in i_remove[1]:
            messages.success(request, msg)
    else:
        for msg in i_remove[1]:
            messages.error(request, i_remove[1])
    return redirect('wishList:dashboard')

def delete_item(request, id):
    if request.method == 'POST':
        u_id = request.session['id']
        d_item = WishList.objects.item_delete(id, u_id)
        if d_item[0] == True:
            messages.success(request, d_item[1])
        else:
            messages.error(request, d_item[1])
    return redirect('wishList:dashboard')

def logout(request):
    request.session.clear()
    messages.success(request, 'You have successfully logged out')
    return redirect('login:login')

apps/wishList/templates/wishList/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>My Wish List</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/skeleton/2.0.4/skeleton.css">
    <link rel="stylesheet" href="static/wishList/index-style.css">
  </head>
  <nav>
    <h3>Hello, {{ name.first_name }}!</h3>
    <a class = "button button-primary" href="{% url 'wishList:logout' %}">Logout</a>
  </nav>
  <body>
    <div class="messages">
      {% if messages %}
        {% for message in messages %}
          <p>{{ message }}</p>
        {% endfor %}
      {% endif %}
    </div>
<h5>Your Wish List:</h5>
<table class="user_table">
  <tr>
    <th>Item</th>
    <th>Added by</th>
    <th>Date Added</th>
    <th>Action</th>
  </tr>
  {% for item in user_items %}
  <tr>
    <td><a href="{% url 'wishList:wish_item' item.id %}">{{ item.item }}</a></td>
    <td>{{ item.created_by.first_name }}</td>
    <td>{{ item.created_at }}</td>
    {% if item.created_by.id != name.id %}
    <td><a class="button" href="{% url 'wishList:remove_item' item.id %}">Remove from my Wishlist</a></td>
    {% elif item.created_by.id == name.id %}
    <form class="delete" action="{% url 'wishList:delete_item' item.id %}" method="post">
      {% csrf_token %}
      <td><input type="submit" name="submit" value="Delete"></td>
    </form>
    {% endif %}
  </tr>
  {% endfor %}
</table>
<h5>Other User's Wish List</h5>
<table class="all_table">
  <tr>
    <th>Item</th>
    <th>Added by</th>
    <th>Date Added</th>
    <th>Action</th>
  </tr>
  {% for wish in other_items %}
  <tr>
    <td>{{ wish.item }}</td>
    <td>{{ wish.created_by.first_name }}</td>
    <td>{{ wish.created_at }}</td>
    <td><a class="button" href="{% url 'wishList:update_list' wish.id %}">Add to my Wishlist</a></td>
  {% endfor %}
  </tr>
</table>
<a class="button button-primary" id="add_item" href="{% url 'wishList:new_item' %}">Add Item</a>
  </body>
</html>

apps/wishList/templates/wishList/item.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{{ item.item }}</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/skeleton/2.0.4/skeleton.css">
    <style media="screen">
      nav{
        margin-bottom: 45px;
      }
      a {
        margin: 10px 15px;
      }
      a#home{
        margin-left: 800px;
      }
      h2, h5 {
        margin-bottom: 50px;
      }
      p{
        margin-bottom: 10px;
      }
    </style>
  </head>
  <nav>
    <a class = "button" id="home" href="{% url 'wishList:dashboard' %}">Home</a>
    <a class = "button button-primary" href="{% url 'wishList:logout' %}">Logout</a>
  </nav>
  <body>

    <h2>{{ item.item }}</h2>
    <h5>Users who added this product/item under their wish list:</h5>
    {% for user in users %}
    <p>{{ user.first_name }}</p>
    {% endfor %}
  </body>
</html>

apps/wishList/templates/wishList/new_item.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Create Item</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/skeleton/2.0.4/skeleton.css">
    <style media="screen">
      a#home{
        margin-right: 15px;
        margin-left: 600px;
      }
      body{
        padding: 10px 50px;
      }
      .messages{
        color: green;
      }
    </style>
  </head>
  <nav>
    <a class = "button" id="home" href="{% url 'wishList:dashboard' %}">Home</a>
    <a class = "button button-primary" href="{% url 'wishList:logout' %}">Logout</a>
  </nav>
  <body>
    <div class="messages">
      {% if messages %}
        {% for message in messages %}
          {{ message}}
        {% endfor %}
      {% endif %}
    </div>
    <form class="add_item" action="{% url 'wishList:add_item' %}" method="post">
      {% csrf_token %}
    <label for="item">Item/Product: <input type="text" name="item"></label>
    <input type="submit" name="submit" value="Add">
    </form>
  </body>
</html>